#! /bin/bash
#$ -S /bin/bash
#SBATCH -J 'mv_gwas_fiadjbmi_hdl_tg_ml'
#SBATCH -D  ''

module load gcc/11.2.0
module load R/4.3.1

WD="" #your working directory

Rscript $WD/code/2_running_mv_gwas/2_run_fiadjbmi_hdl_tg_ml.R
